// This file is not supposed to be edited.
// It is generated by the Firebase CLI.

export const firebaseConfig = {
  apiKey: "AIzaSyDysWRwkAvPO0OpT84oWH_IWfbKONegzvY",
  authDomain: "studio-7631087921-85112.firebaseapp.com",
  projectId: "studio-7631087921-85112",
  storageBucket: "studio-7631087921-85112.appspot.com",
  messagingSenderId: "508157075364",
  appId: "1:508157075364:web:220fecade96d8e0f4f2b31",
};
