-- Drop existing tables
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.transactions CASCADE;
DROP TABLE IF EXISTS public.payment_methods CASCADE;
DROP TABLE IF EXISTS public.sell_orders CASCADE;
DROP TABLE IF EXISTS public.chat_requests CASCADE;
DROP TABLE IF EXISTS public.reports CASCADE;
DROP TABLE IF EXISTS public.feedback CASCADE;
DROP TABLE IF EXISTS public.daily_rewards CASCADE;
DROP TABLE IF EXISTS public.admin_users CASCADE;

-- Users Table
CREATE TABLE public.users (
    id uuid NOT NULL PRIMARY KEY,
    numeric_id character varying UNIQUE,
    email character varying,
    phone_number character varying,
    display_name character varying,
    photo_url character varying,
    balance numeric(15, 2) DEFAULT 0.00,
    hold_balance numeric(15, 2) DEFAULT 0.00,
    created_at timestamp with time zone,
    inviter_uid uuid,
    claimed_user_rewards text[],
    payment_methods jsonb,
    session_id character varying,
    CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Payment Methods (for Admin) Table
CREATE TABLE public.payment_methods (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type character varying NOT NULL,
    bank_name character varying,
    account_holder_name character varying,
    account_number character varying,
    ifsc_code character varying,
    upi_holder_name character varying,
    upi_id character varying,
    usdt_wallet_address character varying,
    provider character varying,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);

-- Orders Table
CREATE TABLE public.orders (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
    order_id character varying UNIQUE,
    amount numeric(15, 2),
    base_amount numeric(15, 2),
    bonus_percentage integer,
    payment_type character varying,
    payment_provider character varying,
    status character varying,
    utr character varying,
    screenshot_url character varying,
    cancellation_reason character varying,
    rejection_reason character varying,
    verification_result text,
    admin_payment_method_id bigint REFERENCES public.payment_methods(id),
    seller_id uuid REFERENCES public.users(id),
    seller_withdrawal_details jsonb,
    created_at timestamp with time zone DEFAULT now(),
    submitted_at timestamp with time zone,
    matched_sell_order_id bigint,
    ocr_amount_match boolean,
    ocr_utr_match boolean,
    ocr_upi_match boolean,
    ocr_name_match boolean,
    ocr_date_match boolean,
    ocr_status_match boolean,
    ocr_raw_text text
);

-- Sell Orders Table
CREATE TABLE public.sell_orders (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
    order_id character varying UNIQUE,
    amount numeric(15, 2),
    remaining_amount numeric(15, 2),
    status character varying,
    withdrawal_method jsonb,
    matched_buy_orders jsonb,
    utr character varying,
    failure_reason character varying,
    created_at timestamp with time zone DEFAULT now(),
    completed_at timestamp with time zone
);

-- Transactions Table
CREATE TABLE public.transactions (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
    order_id character varying,
    amount numeric(15, 2),
    description text,
    type character varying,
    created_at timestamp with time zone DEFAULT now()
);

-- Chat Requests Table
CREATE TABLE public.chat_requests (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES public.users(id),
    user_numeric_id character varying,
    entered_identifier character varying NOT NULL,
    status character varying NOT NULL,
    chat_history jsonb,
    agent_id character varying,
    agent_joined_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

-- Reports Table
CREATE TABLE public.reports (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id character varying UNIQUE,
    user_id uuid REFERENCES public.users(id),
    user_numeric_id character varying,
    order_id character varying,
    display_order_id character varying,
    order_type character varying,
    problem_type character varying,
    message text,
    screenshot_url text,
    video_url text,
    created_at timestamp with time zone DEFAULT now(),
    status character varying,
    resolution_message text
);

-- Feedback Table
CREATE TABLE public.feedback (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES public.users(id),
    user_numeric_id character varying,
    message text,
    created_at timestamp with time zone DEFAULT now()
);

-- Daily Rewards Table
CREATE TABLE public.daily_rewards (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL REFERENCES public.users(id),
    date date NOT NULL,
    claimed_task_ids text[],
    CONSTRAINT daily_rewards_user_id_date_key UNIQUE (user_id, date)
);

-- Admin Users Table (for is_admin function)
CREATE TABLE public.admin_users (
    id SERIAL PRIMARY KEY,
    phone_number TEXT NOT NULL UNIQUE
);

-- Insert admin phone numbers
INSERT INTO public.admin_users (phone_number) VALUES
('9060873927'),
('7050396570'),
('7307081891'),
('9798630209'),
('9199604613')
ON CONFLICT (phone_number) DO NOTHING;


-- Function to check if a user is an admin
create or replace function is_admin(user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  return exists (
    select 1
    from admin_users
    where admin_users.phone_number = (select raw_user_meta_data->>'phone' from auth.users where id = user_id)
  );
end;
$$;


-- =============================================
-- ========== ROW LEVEL SECURITY (RLS) =========
-- =============================================

-- Policies for users table
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public user profile insert" ON public.users;
CREATE POLICY "Allow public user profile insert"
    ON public.users FOR INSERT
    WITH CHECK (true);

DROP POLICY IF EXISTS "Users can update their own profile." ON public.users;
CREATE POLICY "Users can update their own profile."
    ON public.users FOR UPDATE
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can view their own profile." ON public.users;
CREATE POLICY "Users can view their own profile."
    ON public.users FOR SELECT
    USING (auth.uid() = id);

DROP POLICY IF EXISTS "Allow admins full access on users" ON public.users;
CREATE POLICY "Allow admins full access on users"
    ON public.users FOR ALL
    USING (is_admin(auth.uid()))
    WITH CHECK (is_admin(auth.uid()));

-- Policies for payment_methods table (Admin only)
ALTER TABLE public.payment_methods ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow admins full access on payment_methods" ON public.payment_methods;
CREATE POLICY "Allow admins full access on payment_methods"
    ON public.payment_methods FOR ALL
    USING (is_admin(auth.uid()));

-- Policies for orders table
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage their own orders" ON public.orders;
CREATE POLICY "Users can manage their own orders"
    ON public.orders FOR ALL
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow admins full access on orders" ON public.orders;
CREATE POLICY "Allow admins full access on orders"
    ON public.orders FOR ALL
    USING (is_admin(auth.uid()));

-- Policies for sell_orders table
ALTER TABLE public.sell_orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage their own sell_orders" ON public.sell_orders;
CREATE POLICY "Users can manage their own sell_orders"
    ON public.sell_orders FOR ALL
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow admins full access on sell_orders" ON public.sell_orders;
CREATE POLICY "Allow admins full access on sell_orders"
    ON public.sell_orders FOR ALL
    USING (is_admin(auth.uid()));

-- Policies for transactions table
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view their own transactions" ON public.transactions;
CREATE POLICY "Users can view their own transactions"
    ON public.transactions FOR SELECT
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow admins full access on transactions" ON public.transactions;
CREATE POLICY "Allow admins full access on transactions"
    ON public.transactions FOR ALL
    USING (is_admin(auth.uid()));

-- Policies for chat_requests table
ALTER TABLE public.chat_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage their own chat requests" ON public.chat_requests;
CREATE POLICY "Users can manage their own chat requests"
    ON public.chat_requests FOR ALL
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow admins full access on chat_requests" ON public.chat_requests;
CREATE POLICY "Allow admins full access on chat_requests"
    ON public.chat_requests FOR ALL
    USING (is_admin(auth.uid()));

-- Policies for reports table
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage their own reports" ON public.reports;
CREATE POLICY "Users can manage their own reports"
    ON public.reports FOR ALL
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow admins full access on reports" ON public.reports;
CREATE POLICY "Allow admins full access on reports"
    ON public.reports FOR ALL
    USING (is_admin(auth.uid()));

-- Policies for feedback table
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can submit feedback" ON public.feedback;
CREATE POLICY "Users can submit feedback"
    ON public.feedback FOR INSERT
    WITH CHECK (auth.uid() = user_id);
    
DROP POLICY IF EXISTS "Allow admins full access on feedback" ON public.feedback;
CREATE POLICY "Allow admins full access on feedback"
    ON public.feedback FOR ALL
    USING (is_admin(auth.uid()));

-- Policies for daily_rewards table
ALTER TABLE public.daily_rewards ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage their own daily_rewards" ON public.daily_rewards;
CREATE POLICY "Users can manage their own daily_rewards"
    ON public.daily_rewards FOR ALL
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow admins full access on daily_rewards" ON public.daily_rewards;
CREATE POLICY "Allow admins full access on daily_rewards"
    ON public.daily_rewards FOR ALL
    USING (is_admin(auth.uid()));

-- =============================================
-- ========== DATABASE FUNCTIONS (RPC) =========
-- =============================================

-- Function to create a sell order
CREATE OR REPLACE FUNCTION create_sell_order(
    p_user_id uuid,
    p_amount numeric,
    p_withdrawal_method jsonb
) RETURNS void AS $$
DECLARE
    new_balance numeric;
BEGIN
    -- Decrement user's balance
    UPDATE public.users
    SET balance = balance - p_amount
    WHERE id = p_user_id
    RETURNING balance INTO new_balance;

    IF new_balance < 0 THEN
        -- Rollback balance change and raise error
        UPDATE public.users
        SET balance = balance + p_amount
        WHERE id = p_user_id;
        RAISE EXCEPTION 'Insufficient balance';
    END IF;

    -- Insert the sell order
    INSERT INTO public.sell_orders(user_id, order_id, amount, remaining_amount, status, withdrawal_method)
    VALUES (
        p_user_id,
        'LGPAYSELL' || substr(md5(random()::text), 0, 15),
        p_amount,
        p_amount,
        'pending',
        p_withdrawal_method
    );
END;
$$ LANGUAGE plpgsql;

-- Function to create a buy order and match with sell orders
CREATE OR REPLACE FUNCTION create_buy_order(
    p_user_id uuid,
    p_amount numeric,
    p_base_amount numeric,
    p_bonus_percentage integer,
    p_payment_provider text,
    p_payment_type text
) RETURNS TABLE(order_id text, final_payment_type text) AS $$
DECLARE
    seller_record RECORD;
    new_buy_order_id bigint;
    new_buy_order_oid text;
    payment_method_record RECORD;
BEGIN
    -- Attempt to find a P2P seller first
    SELECT * INTO seller_record
    FROM public.sell_orders
    WHERE status IN ('pending', 'partially_filled')
      AND user_id != p_user_id
      AND remaining_amount >= p_base_amount
    ORDER BY created_at ASC
    LIMIT 1
    FOR UPDATE;

    IF seller_record IS NOT NULL THEN
        -- P2P Match Found
        INSERT INTO public.orders(user_id, order_id, amount, base_amount, bonus_percentage, payment_provider, payment_type, status, seller_id, seller_withdrawal_details, matched_sell_order_id)
        VALUES (
            p_user_id,
            'LGPAY' || substr(md5(random()::text), 0, 15),
            p_amount,
            p_base_amount,
            p_bonus_percentage,
            p_payment_provider,
            'p2p_' || p_payment_type,
            'pending_payment',
            seller_record.user_id,
            seller_record.withdrawal_method,
            seller_record.id
        ) RETURNING id, order_id INTO new_buy_order_id, new_buy_order_oid;

        -- Update sell order
        UPDATE public.sell_orders
        SET
            remaining_amount = seller_record.remaining_amount - p_base_amount,
            status = CASE
                        WHEN seller_record.remaining_amount - p_base_amount <= 0 THEN 'processing'
                        ELSE 'partially_filled'
                     END,
            matched_buy_orders = COALESCE(matched_buy_orders, '[]'::jsonb) || jsonb_build_object(
                'order_id', new_buy_order_oid,
                'buyer_id', p_user_id,
                'amount', p_base_amount,
                'status', 'pending_payment',
                'created_at', now()
            )
        WHERE id = seller_record.id;

        RETURN QUERY SELECT new_buy_order_oid, 'p2p_' || p_payment_type;

    ELSE
        -- No P2P Match, create admin order
        SELECT * INTO payment_method_record
        FROM public.payment_methods
        WHERE type = p_payment_type AND is_active = true
        ORDER BY random()
        LIMIT 1;

        IF payment_method_record IS NULL THEN
            RAISE EXCEPTION 'No active admin payment method available for type %', p_payment_type;
        END IF;

        INSERT INTO public.orders(user_id, order_id, amount, base_amount, bonus_percentage, payment_provider, payment_type, status, admin_payment_method_id)
        VALUES (
            p_user_id,
            'LGPAY' || substr(md5(random()::text), 0, 15),
            p_amount,
            p_base_amount,
            p_bonus_percentage,
            p_payment_provider,
            p_payment_type,
            'pending_payment',
            payment_method_record.id
        ) RETURNING order_id INTO new_buy_order_oid;

        RETURN QUERY SELECT new_buy_order_oid, p_payment_type;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Function to approve a buy order
CREATE OR REPLACE FUNCTION approve_buy_order(p_order_id bigint, p_user_id uuid, p_amount_to_add numeric, p_matched_sell_order_id bigint DEFAULT NULL)
RETURNS void AS $$
DECLARE
    v_order RECORD;
    v_sell_order RECORD;
BEGIN
    -- Update the buy order status to 'completed'
    UPDATE public.orders SET status = 'completed' WHERE id = p_order_id;

    -- Add the amount to the user's balance
    UPDATE public.users SET balance = balance + p_amount_to_add WHERE id = p_user_id;

    -- Create a transaction record for the purchase
    INSERT INTO public.transactions (user_id, order_id, amount, description, type)
    VALUES (p_user_id, (SELECT order_id FROM public.orders WHERE id = p_order_id), p_amount_to_add, 'LGB Purchase', 'buy');

    -- Handle P2P logic if a matched sell order ID is provided
    IF p_matched_sell_order_id IS NOT NULL THEN
        -- Get the sell order
        SELECT * INTO v_sell_order FROM public.sell_orders WHERE id = p_matched_sell_order_id;
        
        -- Update the matched_buy_orders array
        UPDATE public.sell_orders
        SET matched_buy_orders = (
            SELECT jsonb_agg(
                CASE
                    WHEN (elem->>'order_id')::text = (SELECT order_id FROM public.orders WHERE id = p_order_id)
                    THEN jsonb_set(elem, '{status}', '"completed"')
                    ELSE elem
                END
            )
            FROM jsonb_array_elements(v_sell_order.matched_buy_orders) AS elem
        )
        WHERE id = p_matched_sell_order_id;

        -- Check if the sell order is now fully completed
        IF (v_sell_order.remaining_amount <= 0 AND NOT EXISTS (
            SELECT 1 FROM jsonb_array_elements(v_sell_order.matched_buy_orders) AS elem
            WHERE elem->>'status' != 'completed'
        )) THEN
            UPDATE public.sell_orders SET status = 'completed', completed_at = now() WHERE id = p_matched_sell_order_id;
        END IF;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Function to reject a buy order
CREATE OR REPLACE FUNCTION reject_buy_order(p_order_id bigint, p_rejection_reason text)
RETURNS void AS $$
DECLARE
    v_order RECORD;
BEGIN
    -- Fetch the order details
    SELECT * INTO v_order FROM public.orders WHERE id = p_order_id;

    -- Update the buy order status
    UPDATE public.orders SET status = 'failed', rejection_reason = p_rejection_reason WHERE id = p_order_id;

    -- If it was a P2P order, restore the seller's amount
    IF v_order.matched_sell_order_id IS NOT NULL THEN
        UPDATE public.sell_orders
        SET
            remaining_amount = remaining_amount + v_order.base_amount,
            status = 'partially_filled', -- or 'pending' if it was full before
            matched_buy_orders = (
                SELECT jsonb_agg(elem)
                FROM jsonb_array_elements(matched_buy_orders) AS elem
                WHERE (elem->>'order_id')::text != v_order.order_id
            )
        WHERE id = v_order.matched_sell_order_id;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Function to claim daily rewards
CREATE OR REPLACE FUNCTION claim_daily_reward(p_user_id uuid, p_task_id text, p_reward_amount numeric, p_date_string text, p_task_title text)
RETURNS void AS $$
DECLARE
    v_today date := p_date_string::date;
BEGIN
    -- Add reward to user's balance
    UPDATE public.users SET balance = balance + p_reward_amount WHERE id = p_user_id;

    -- Record the transaction
    INSERT INTO public.transactions (user_id, order_id, amount, description, type)
    VALUES (p_user_id, 'REWARD-' || p_task_id || '-' || v_today, p_reward_amount, p_task_title, 'daily_task');

    -- Upsert the daily reward record
    INSERT INTO public.daily_rewards (user_id, date, claimed_task_ids)
    VALUES (p_user_id, v_today, ARRAY[p_task_id])
    ON CONFLICT (user_id, date) DO UPDATE
    SET claimed_task_ids = array_append(daily_rewards.claimed_task_ids, p_task_id);
END;
$$ LANGUAGE plpgsql;

-- Function to claim newbie friend rewards
CREATE OR REPLACE FUNCTION claim_newbie_friend_rewards(p_user_id uuid, p_friend_uids uuid[], p_reward_amount numeric, p_reward_description text)
RETURNS void AS $$
DECLARE
    v_total_reward numeric := array_length(p_friend_uids, 1) * p_reward_amount;
BEGIN
    -- Update user balance
    UPDATE public.users SET balance = balance + v_total_reward WHERE id = p_user_id;
    
    -- Update claimed rewards list
    UPDATE public.users
    SET claimed_newbie_friend_rewards = COALESCE(claimed_newbie_friend_rewards, '{}'::text[]) || p_friend_uids::text[]
    WHERE id = p_user_id;
    
    -- Record one transaction for the batch claim
    INSERT INTO public.transactions (user_id, order_id, amount, description, type)
    VALUES (p_user_id, 'NEWBIE-FRIEND-' || now()::text, v_total_reward, p_reward_description, 'new_user_reward');
END;
$$ LANGUAGE plpgsql;

-- Function to cancel remaining part of a sell order
CREATE OR REPLACE FUNCTION cancel_remaining_sell_order(p_order_id bigint, p_user_id uuid)
RETURNS void AS $$
DECLARE
    v_sell_order RECORD;
BEGIN
    SELECT * INTO v_sell_order FROM public.sell_orders WHERE id = p_order_id AND user_id = p_user_id;

    IF v_sell_order IS NULL THEN
        RAISE EXCEPTION 'Sell order not found or you do not have permission to cancel it.';
    END IF;
    
    IF v_sell_order.remaining_amount <= 0 THEN
        RAISE EXCEPTION 'No remaining amount to cancel.';
    END IF;

    -- Refund the remaining amount to user's balance
    UPDATE public.users SET balance = balance + v_sell_order.remaining_amount WHERE id = p_user_id;
    
    -- Update the sell order
    UPDATE public.sell_orders
    SET
        status = 'completed', -- Or a new 'partially_cancelled' status if you prefer
        failure_reason = 'Partially cancelled by user',
        remaining_amount = 0
    WHERE id = p_order_id;
END;
$$ LANGUAGE plpgsql;
