-- This script will completely reset the public schema of your Supabase database.
-- WARNING: All data in the existing tables will be lost.

-- Drop existing tables in a safe order
DROP TABLE IF EXISTS public.daily_rewards;
DROP TABLE IF EXISTS public.feedback;
DROP TABLE IF EXISTS public.reports;
DROP TABLE IF EXISTS public.chat_requests;
DROP TABLE IF EXISTS public.transactions;
DROP TABLE IF EXISTS public.orders;
DROP TABLE IF EXISTS public.sell_orders;
DROP TABLE IF EXISTS public.payment_methods;
DROP TABLE IF EXISTS public.users;

-- Create users table
CREATE TABLE public.users (
    id uuid NOT NULL PRIMARY KEY,
    numeric_id text UNIQUE,
    display_name text,
    phone_number text UNIQUE,
    email text UNIQUE,
    photo_url text,
    balance numeric DEFAULT 0,
    hold_balance numeric DEFAULT 0,
    inviter_uid uuid,
    payment_methods jsonb,
    claimed_user_rewards text[],
    claimed_newbie_friend_rewards text[],
    session_id text,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);
COMMENT ON TABLE public.users IS 'Stores user profile information.';

-- Create payment_methods table (for admin use)
CREATE TABLE public.payment_methods (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type text,
    bank_name text,
    account_holder_name text,
    account_number text,
    ifsc_code text,
    upi_holder_name text,
    upi_id text,
    usdt_wallet_address text,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);
COMMENT ON TABLE public.payment_methods IS 'Admin-configured payment methods for users to deposit to.';

-- Create orders table (for user buy orders)
CREATE TABLE public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id text UNIQUE,
    user_id uuid REFERENCES public.users(id),
    amount numeric,
    base_amount numeric,
    bonus_percentage numeric,
    status text,
    payment_type text,
    payment_provider text,
    utr text,
    screenshot_url text,
    cancellation_reason text,
    rejection_reason text,
    created_at timestamp with time zone DEFAULT now(),
    submitted_at timestamp with time zone,
    admin_payment_method_id bigint REFERENCES public.payment_methods(id),
    seller_id uuid REFERENCES public.users(id),
    seller_withdrawal_details jsonb,
    matched_sell_order_id bigint,
    ocr_amount_match boolean,
    ocr_utr_match boolean,
    ocr_upi_match boolean,
    ocr_name_match boolean,
    ocr_date_match boolean,
    ocr_status_match boolean,
    ocr_raw_text text
);
COMMENT ON TABLE public.orders IS 'Records user requests to buy LGB.';

-- Create sell_orders table (for user sell orders / P2P)
CREATE TABLE public.sell_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id text UNIQUE,
    user_id uuid REFERENCES public.users(id),
    amount numeric,
    remaining_amount numeric,
    status text,
    withdrawal_method jsonb,
    matched_buy_orders jsonb,
    utr text,
    failure_reason text,
    created_at timestamp with time zone DEFAULT now(),
    completed_at timestamp with time zone
);
COMMENT ON TABLE public.sell_orders IS 'Records user requests to sell LGB, forming the P2P pool.';

-- Create transactions table
CREATE TABLE public.transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.users(id),
    order_id text,
    amount numeric,
    description text,
    type text,
    created_at timestamp with time zone DEFAULT now()
);
COMMENT ON TABLE public.transactions IS 'Logs all balance changes for users (buy, sell, rewards, etc.).';

-- Create chat_requests table
CREATE TABLE public.chat_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.users(id),
    user_numeric_id text,
    entered_identifier text,
    status text,
    created_at timestamp with time zone DEFAULT now(),
    chat_history jsonb,
    agent_id text,
    agent_joined_at timestamp with time zone
);
COMMENT ON TABLE public.chat_requests IS 'Stores user requests for live agent support.';

-- Create reports table
CREATE TABLE public.reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id text UNIQUE,
    user_id uuid REFERENCES public.users(id),
    user_numeric_id text,
    order_id text,
    display_order_id text,
    order_type text,
    problem_type text,
    message text,
    screenshot_url text,
    video_url text,
    created_at timestamp with time zone DEFAULT now(),
    status text,
    resolution_message text
);
COMMENT ON TABLE public.reports IS 'Stores user-submitted problem reports about orders.';

-- Create feedback table
CREATE TABLE public.feedback (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.users(id),
    user_numeric_id text,
    message text,
    created_at timestamp with time zone DEFAULT now()
);
COMMENT ON TABLE public.feedback IS 'Stores user-submitted feedback and suggestions.';

-- Create daily_rewards table
CREATE TABLE public.daily_rewards (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.users(id) NOT NULL,
    date date NOT NULL,
    claimed_task_ids text[],
    UNIQUE (user_id, date)
);
COMMENT ON TABLE public.daily_rewards IS 'Tracks daily task rewards claimed by users.';

-- Enable Row Level Security (RLS) for all tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sell_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_rewards ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can see their own profile" ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.users FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "Allow authenticated users to read minimal user data" ON public.users FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can manage their own orders" ON public.orders FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own sell orders" ON public.sell_orders FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can see their own transactions" ON public.transactions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own daily rewards" ON public.daily_rewards FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Allow authenticated read for admin payment methods" ON public.payment_methods FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users can manage their own chat requests" ON public.chat_requests FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own reports" ON public.reports FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own feedback" ON public.feedback FOR ALL USING (auth.uid() = user_id);

-- Database Functions (RPC)

-- Function to create a sell order
CREATE OR REPLACE FUNCTION create_sell_order(p_user_id uuid, p_amount numeric, p_withdrawal_method jsonb)
RETURNS void AS $$
DECLARE
  user_balance numeric;
  new_order_id text;
BEGIN
  SELECT balance INTO user_balance FROM public.users WHERE id = p_user_id;
  IF user_balance IS NULL OR user_balance < p_amount THEN
    RAISE EXCEPTION 'Insufficient balance';
  END IF;

  UPDATE public.users SET balance = balance - p_amount WHERE id = p_user_id;
  new_order_id := 'LGPAYSELL' || to_char(now(), 'YYYYMMDD') || substr(md5(random()::text), 1, 10);

  INSERT INTO public.sell_orders (user_id, amount, remaining_amount, withdrawal_method, status, order_id)
  VALUES (p_user_id, p_amount, p_amount, p_withdrawal_method, 'pending', new_order_id);
END;
$$ LANGUAGE plpgsql;

-- Function to create a buy order with P2P fallback logic
CREATE OR REPLACE FUNCTION create_buy_order(p_user_id uuid, p_amount numeric, p_base_amount numeric, p_bonus_percentage numeric, p_payment_provider text, p_payment_type text)
RETURNS TABLE(order_id text, final_payment_type text) AS $$
DECLARE
  v_order_id text;
  v_final_payment_type text := p_payment_type;
  seller_record record;
  admin_method_record record;
BEGIN
  v_order_id := 'LGPAY' || to_char(now(), 'YYYYMMDD') || substr(md5(random()::text), 1, 10);

  IF p_payment_type = 'p2p_upi' THEN
    SELECT * INTO seller_record FROM public.sell_orders
    WHERE status IN ('pending', 'partially_filled')
      AND user_id != p_user_id
      AND remaining_amount >= p_base_amount
      AND withdrawal_method->>'type' = 'upi'
    ORDER BY created_at ASC
    LIMIT 1
    FOR UPDATE;

    IF FOUND THEN
      INSERT INTO public.orders (order_id, user_id, amount, base_amount, bonus_percentage, status, payment_type, payment_provider, seller_id, seller_withdrawal_details, matched_sell_order_id)
      VALUES (v_order_id, p_user_id, p_amount, p_base_amount, p_bonus_percentage, 'pending_payment', p_payment_type, p_payment_provider, seller_record.user_id, seller_record.withdrawal_method, seller_record.id);
      
      UPDATE public.sell_orders
      SET
        remaining_amount = seller_record.remaining_amount - p_base_amount,
        status = CASE WHEN (seller_record.remaining_amount - p_base_amount) = 0 THEN 'processing' ELSE 'partially_filled' END,
        matched_buy_orders = COALESCE(matched_buy_orders, '[]'::jsonb) || jsonb_build_object(
          'buy_order_id', (SELECT id FROM public.orders WHERE order_id = v_order_id),
          'buyer_order_id', v_order_id,
          'buyer_id', p_user_id,
          'amount', p_base_amount,
          'status', 'pending_payment',
          'created_at', now()
        )
      WHERE id = seller_record.id;
      
      RETURN QUERY SELECT v_order_id, v_final_payment_type;
      RETURN;
    END IF;
  END IF;

  v_final_payment_type := REPLACE(p_payment_type, 'p2p_', '');
  
  SELECT * INTO admin_method_record FROM public.payment_methods
  WHERE type = v_final_payment_type AND is_active = true
  ORDER BY random()
  LIMIT 1;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No active payment method available. Please contact support.';
  END IF;

  INSERT INTO public.orders (order_id, user_id, amount, base_amount, bonus_percentage, status, payment_type, payment_provider, admin_payment_method_id)
  VALUES (v_order_id, p_user_id, p_amount, p_base_amount, p_bonus_percentage, 'pending_payment', v_final_payment_type, p_payment_provider, admin_method_record.id);

  RETURN QUERY SELECT v_order_id, v_final_payment_type;
END;
$$ LANGUAGE plpgsql;

-- Function to approve a buy order
CREATE OR REPLACE FUNCTION approve_buy_order(p_order_id bigint, p_user_id uuid, p_amount_to_add numeric, p_matched_sell_order_id bigint DEFAULT NULL)
RETURNS void AS $$
DECLARE
  buy_order record;
  seller_user_id uuid;
BEGIN
  UPDATE public.orders SET status = 'completed' WHERE id = p_order_id;
  
  INSERT INTO public.transactions (user_id, order_id, amount, description, type)
  VALUES (p_user_id, (SELECT order_id FROM public.orders WHERE id = p_order_id), p_amount_to_add, 'Purchase of LGB', 'buy_credit');

  UPDATE public.users SET balance = balance + p_amount_to_add WHERE id = p_user_id;

  IF p_matched_sell_order_id IS NOT NULL THEN
    SELECT user_id INTO seller_user_id FROM public.sell_orders WHERE id = p_matched_sell_order_id;

    IF seller_user_id IS NOT NULL THEN
      INSERT INTO public.transactions (user_id, order_id, amount, description, type)
      VALUES (seller_user_id, (SELECT order_id FROM public.sell_orders WHERE id = p_matched_sell_order_id), (SELECT base_amount FROM public.orders WHERE id = p_order_id), 'P2P Sale Completed', 'p2p_sell');
      
      UPDATE public.sell_orders
      SET status = 'completed', completed_at = now()
      WHERE id = p_matched_sell_order_id AND remaining_amount <= 0;
    END IF;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- Function to reject or cancel a buy order
CREATE OR REPLACE FUNCTION reject_buy_order(p_order_id bigint, p_rejection_reason text)
RETURNS void AS $$
DECLARE
  buy_order record;
  sell_order record;
  matched_order jsonb;
  new_matched_buy_orders jsonb := '[]'::jsonb;
BEGIN
  SELECT * INTO buy_order FROM public.orders WHERE id = p_order_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Buy order not found';
  END IF;
  
  UPDATE public.orders
  SET status = 'failed', rejection_reason = p_rejection_reason
  WHERE id = p_order_id;

  IF buy_order.matched_sell_order_id IS NOT NULL THEN
    SELECT * INTO sell_order FROM public.sell_orders WHERE id = buy_order.matched_sell_order_id FOR UPDATE;

    IF FOUND THEN
      UPDATE public.sell_orders
      SET
        remaining_amount = sell_order.remaining_amount + buy_order.base_amount,
        status = 'partially_filled'
      WHERE id = sell_order.id;

      FOR matched_order IN SELECT * FROM jsonb_array_elements(sell_order.matched_buy_orders)
      LOOP
        IF (matched_order->>'buy_order_id')::bigint != buy_order.id THEN
          new_matched_buy_orders := new_matched_buy_orders || matched_order;
        END IF;
      END LOOP;

      UPDATE public.sell_orders
      SET matched_buy_orders = new_matched_buy_orders
      WHERE id = sell_order.id;
    END IF;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- Function to cancel remaining amount of a sell order
CREATE OR REPLACE FUNCTION cancel_remaining_sell_order(p_order_id bigint, p_user_id uuid)
RETURNS void AS $$
DECLARE
  sell_order record;
BEGIN
  SELECT * INTO sell_order FROM public.sell_orders WHERE id = p_order_id AND user_id = p_user_id FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Sell order not found or user mismatch';
  END IF;
  
  IF sell_order.remaining_amount <= 0 THEN
    RAISE EXCEPTION 'No remaining amount to cancel';
  END IF;
  
  UPDATE public.users SET balance = balance + sell_order.remaining_amount WHERE id = p_user_id;

  INSERT INTO public.transactions (user_id, order_id, amount, description, type)
  VALUES (p_user_id, sell_order.order_id, sell_order.remaining_amount, 'Refund for cancelled sell order', 'sell_cancel_refund');
  
  UPDATE public.sell_orders
  SET
    remaining_amount = 0,
    status = CASE WHEN sell_order.amount = sell_order.remaining_amount THEN 'failed' ELSE 'completed' END,
    failure_reason = 'User cancelled remaining amount'
  WHERE id = p_order_id;
END;
$$ LANGUAGE plpgsql;

-- Function to claim daily rewards
CREATE OR REPLACE FUNCTION claim_daily_reward(p_user_id uuid, p_task_id text, p_reward_amount numeric, p_date_string text, p_task_title text)
RETURNS void AS $$
DECLARE
  v_today date := to_date(p_date_string, 'YYYY-MM-DD');
BEGIN
  INSERT INTO public.daily_rewards (user_id, date, claimed_task_ids)
  VALUES (p_user_id, v_today, ARRAY[p_task_id])
  ON CONFLICT (user_id, date)
  DO UPDATE SET claimed_task_ids = daily_rewards.claimed_task_ids || excluded.claimed_task_ids;

  UPDATE public.users SET balance = balance + p_reward_amount WHERE id = p_user_id;

  INSERT INTO public.transactions (user_id, amount, description, type, order_id)
  VALUES (p_user_id, p_reward_amount, p_task_title, 'daily_task', 'TASK-' || p_task_id || '-' || p_date_string);
END;
$$ LANGUAGE plpgsql;

-- Function to claim newbie friend rewards
CREATE OR REPLACE FUNCTION claim_newbie_friend_rewards(p_user_id uuid, p_friend_uids uuid[], p_reward_amount numeric, p_reward_description text)
RETURNS void AS $$
DECLARE
  total_reward numeric := array_length(p_friend_uids, 1) * p_reward_amount;
  friend_uid_text text;
BEGIN
  UPDATE public.users SET balance = balance + total_reward WHERE id = p_user_id;

  INSERT INTO public.transactions (user_id, amount, description, type, order_id)
  VALUES (p_user_id, total_reward, p_reward_description, 'team_bonus', 'NFR-' || to_char(now(), 'YYYYMMDDHH24MISS'));

  FOREACH friend_uid_text IN ARRAY (SELECT ARRAY(SELECT unnest(p_friend_uids)::text))
  LOOP
    UPDATE public.users
    SET claimed_newbie_friend_rewards = array_append(coalesce(claimed_newbie_friend_rewards, '{}'), friend_uid_text)
    WHERE id = p_user_id;
  END LOOP;
END;
$$ LANGUAGE plpgsql;
