"use strict";
// This file defines the collections to be exported and their transformation logic.
Object.defineProperty(exports, "__esModule", { value: true });
exports.collectionsToExport = void 0;
// Helper to convert Firestore Timestamps to ISO strings
const transformTimestamps = (data) => {
    for (const key in data) {
        if (data[key] && typeof data[key] === 'object' && data[key]._seconds !== undefined) {
            try {
                data[key] = new Date(data[key]._seconds * 1000).toISOString();
            }
            catch (e) {
                console.warn(`Invalid timestamp for key ${key}, setting to null.`);
                data[key] = null;
            }
        }
    }
    return data;
};
exports.collectionsToExport = [
    {
        collectionId: 'users',
        tableName: 'users',
        isSubcollection: false,
        transform: (doc) => {
            const data = transformTimestamps(doc);
            return {
                id: data.uid,
                numeric_id: data.numericId,
                email: data.email,
                phone_number: data.phoneNumber,
                display_name: data.displayName,
                photo_url: data.photoURL,
                balance: data.balance || 0,
                hold_balance: data.holdBalance || 0,
                created_at: data.createdAt || new Date().toISOString(),
                inviter_uid: data.inviterUid,
                claimed_user_rewards: data.claimedUserRewards,
                payment_methods: data.paymentMethods,
                session_id: data.sessionId,
            };
        },
    },
    {
        collectionId: 'orders',
        tableName: 'orders',
        isSubcollection: true,
        transform: (doc) => {
            const data = transformTimestamps(doc);
            return {
                // id is auto-generated by Supabase
                user_id: data.userId,
                order_id: data.orderId,
                amount: data.amount,
                base_amount: data.baseAmount,
                bonus_percentage: data.bonusPercentage,
                payment_type: data.paymentType,
                payment_provider: data.paymentProvider,
                status: data.status,
                utr: data.utr,
                screenshot_url: data.screenshotURL,
                cancellation_reason: data.cancellationReason,
                rejection_reason: data.rejectionReason,
                verification_result: data.verificationResult,
                admin_payment_method_id: null,
                seller_id: data.sellerId,
                seller_withdrawal_details: data.sellerWithdrawalDetails,
                created_at: data.createdAt || new Date().toISOString(),
                submitted_at: data.submittedAt,
            };
        },
    },
    {
        collectionId: 'sellOrders',
        tableName: 'sell_orders',
        isSubcollection: true,
        transform: (doc) => {
            const data = transformTimestamps(doc);
            return {
                user_id: data.userId,
                order_id: data.orderId,
                amount: data.amount,
                remaining_amount: data.remainingAmount,
                status: data.status,
                withdrawal_method: data.withdrawalMethod,
                matched_buy_orders: data.matchedBuyOrders,
                utr: data.utr,
                failure_reason: data.failureReason,
                created_at: data.createdAt || new Date().toISOString(),
                completed_at: data.completedAt,
            };
        },
    },
    {
        collectionId: 'transactions',
        tableName: 'transactions',
        isSubcollection: true,
        transform: (doc) => {
            const data = transformTimestamps(doc);
            return {
                user_id: data.userId,
                order_id: data.orderId,
                amount: data.amount,
                description: data.description,
                type: data.type,
                created_at: data.createdAt || new Date().toISOString(),
            };
        },
    },
    {
        collectionId: 'paymentMethods',
        tableName: 'payment_methods',
        isSubcollection: false,
        transform: (doc) => {
            const data = transformTimestamps(doc);
            return {
                type: data.type,
                bank_name: data.bankName,
                account_holder_name: data.accountHolderName,
                account_number: data.accountNumber,
                ifsc_code: data.ifscCode,
                upi_holder_name: data.upiHolderName,
                upi_id: data.upiId,
                usdt_wallet_address: data.usdtWalletAddress,
            };
        },
    },
];
